### ISSUE TITLE
Where is baselines.run_multiagent_unity?

### ISSUE THREAD

**Issue by icaro56** [Sohojoe/MarathonEnvsBaselines#2]
python -m baselines.run_multiagent_unity --alg=ppo2 --env="envs\hopper-x16\Unity Environment.exe" --num_timesteps=1e6 --save_path=models\hopper_1m_ppo2

When I try to run this code, my prompt does not find the module: No module named baselines.run_multiagent_unity

**Comment by icaro56** [comment]
Ok, As I installed baseline by pip too, your new files I had not

**Comment by Sohojoe** [comment]
@icaro56: 

hmm - you should not need to install Baselines. The `-m` python switch makes the baselines folder act like a module. 

The problem may be the dependencies. Maybe I need to update the docs to specify that

```
cd baselines
pip install -e .
```
