### ISSUE TITLE
Did you find out why you did not get good results with stable-baseline algorithms?

### ISSUE THREAD

**Issue by icaro56** [Sohojoe/MarathonEnvsBaselines#3]
I'm trying to train agents only without visual observations with DQN. Multiagents with one Brain.

Do you advise using baseline or stable algorithms?

What files should I begin to see to start my workouts with DQN? I apologize for the newbie questions.

**Comment by Sohojoe** [comment]
Hi @icaro56, 

it does not look like DQN supports multi-environments based on this [link](https://github.com/openai/baselines/issues/642) nor does [stable.baselines](https://github.com/hill-a/stable-baselines#implemented-algorithms) - if you really need DQN it might be worth asking for help on baselines and/or stable.baselines and I can help you with the Unity part. If you don't need DQN (i.e. just want to try with a few different algorithms), then I would advise starting with normal ml-agents + PPO as that will probably be as good and as fast as anything else.

**Comment by Sohojoe** [comment]
oh and I did not get stable.baselines working:

* I've been able to train with baselines.PPO2 and baselines.A2C - I'm using continuous observations so I believe these are the only algorithms that support continuous observation - however, I think ACER and ACKTR (+ PPO2 & A@C) will support multiagent discrete.
* Note: if you are using continuous observations - know that it's currently not possible to save models that trained using Normalize - If try to pre-normalized your observations (keep them to -1 to +1 or 0 to +1) then you won't need to normalize them
* I've still not been able to get stable baselines to train (only tried PPO2) - I saw that they have pushed a fix so it may be worth trying their latest code.

**Comment by icaro56** [comment]
Thank you.

What do you mean by continuous observations?

**Comment by Sohojoe** [comment]
so long as all the agents are using the same brain you will be ok. Vectorized Environments mean it expects a list of observations etc. This is how ml-agents works by default and my code handles linking between ml-agents and a Vectorized Environment in gym

100 agents will be find too.

for your observations - all your observations should be bools (discrete value / a float that is 0 or 1) or float that is between -1 and 1 or 0 and 1 (discrete). You can use larger values if the algorithm supports normalization, however, all the normalization is doing is taking a running average a squashing it -1 to 1. The default normalization algorithm in openai.baselines does not save properly. so it is better if you normalize them (i.e. divide by the max value) yourself. Don't use ints to reference states, you should use a bool for each state.

**Comment by icaro56** [comment]
Thank you. 

My observations are binary flag or hybrid, as I put in this link: https://github.com/Unity-Technologies/ml-agents/issues/802

So, i will have to change these observations. But, I think the hybrid observation will work because are float 0 or 1.

**Comment by icaro56** [comment]
Can you share with me some paper that explain why to use bools?

**Comment by Sohojoe** [comment]
using float 0 or 1 is fine as all goes into a vector. I can't think of a paper specific to RL unity state this as a best practice in their docs - 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Best-Practices.md#vector-observations

the way I think about it is in terms of basic ML supervised learning where one is either predicting discrete categories (think images of cats and dogs - each category is binary / one-hot encoded) or predicting a continuous value (think house sale price)
