### ISSUE TITLE
Can I update openai/baseline?

### ISSUE THREAD

**Issue by icaro56** [Sohojoe/MarathonEnvsBaselines#4]
If I update the openai/baseline, what files that you created and/or modified that will I need to create and/or modify?

modify this file: baselines/common/cmd_util.py

create these files: 
run_multiagent_unity.py
run_unity.py
baselines\common\vec_env\unity_vec_env.py
baselines\ddpg\main_unity.py

**Comment by Sohojoe** [comment]
my code is a bit messy! - I think it is just these:

baselines/run_unity.py
baselines/run_multiagent_unity.py
baselines/common/vec_env/unity_vec_env.py - this is the vectorized enviroment wrapper for ml-agents
baselines/common/cmd_util.py - i added `make_multi_unity_vec_env`

re - baselines\ddpg\main_unity.py - i'm not sure i got this working

**Comment by icaro56** [comment]
Thank you.
